project_id = "pxpppaxoxzkxsjlubrts"

[functions.ai-explain]
verify_jwt = false

[functions.find-resources]
verify_jwt = false

[functions.ai-chat-solver]
verify_jwt = false

[functions.analyze-syllabus]
verify_jwt = false
